name: film_link
description: "Film Link"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & DI
  flutter_riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  
  # Navigation
  go_router: ^16.2.4
  
  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Authentication & Storage
  supabase_flutter: ^2.10.2
  flutter_secure_storage: ^9.2.4
  
  # Functional Programming
  dartz: ^0.10.1
  dartx: ^1.2.0
  
  # UI
  super_sliver_list: ^0.4.1
  
  # Logging
  logging: ^1.3.0
  
  # Utils
  equatable: ^2.0.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.1
  riverpod_lint: ^3.0.1

flutter:
  uses-material-design: true
